// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBna1QJkW4u4-cFyX_1cQIeMzZy887ZPtk',
    appId: '1:674705689666:web:dfe3bfbbe760be2c1cf1db',
    messagingSenderId: '674705689666',
    projectId: 'iittnif',
    authDomain: 'iittnif.firebaseapp.com',
    storageBucket: 'iittnif.appspot.com',
    measurementId: 'G-TLYRWTQYC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK3mv4M-9W4jjVFv42gPYDqgfWs_QjE3g',
    appId: '1:674705689666:android:c5759cd6b30e10481cf1db',
    messagingSenderId: '674705689666',
    projectId: 'iittnif',
    storageBucket: 'iittnif.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeAvr_5f8qhKQOMLUNo-3lGQynW1wDR8o',
    appId: '1:674705689666:ios:2189cd602ba4329c1cf1db',
    messagingSenderId: '674705689666',
    projectId: 'iittnif',
    storageBucket: 'iittnif.appspot.com',
    iosBundleId: 'com.example.iittnif',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeAvr_5f8qhKQOMLUNo-3lGQynW1wDR8o',
    appId: '1:674705689666:ios:2189cd602ba4329c1cf1db',
    messagingSenderId: '674705689666',
    projectId: 'iittnif',
    storageBucket: 'iittnif.appspot.com',
    iosBundleId: 'com.example.iittnif',
  );
}
